services:
  postgres:
    image: postgres
    environment:
        - POSTGRES_PASSWORD=pranay@123
    ports:
        - 5432:5432
    volumes:
        - pgdata:/var/lib/postgresql/data
volumes:
    pgdata:
    
    